name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pipx install algokit==2.10.2
      - run: algokit localnet start
      - run: bun install --frozen-lockfile
      - run: bun test
      - run: bun check:lint
      - run: bun check:types
