name: PR

on:
  pull_request:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start LocalNet
        run: pnpm run localnet start

      - name: Lint
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format

      - name: Check types
        run: pnpm run check-types

      - name: Test
        run: pnpm run test

      - name: Check changelog
        uses: joe-p/semfrag/actions/check@e4ce6e37a786a2d283ce7edbaf235af5aa8d48b7 # v0.9.0
        with:
          require-fragment-for: ^src/
